# Generated by Django 4.0.5 on 2022-06-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PtzAccountUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('id_image', models.CharField(blank=True, max_length=255, null=True)),
                ('business_type', models.CharField(blank=True, max_length=255, null=True)),
                ('second_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('shop_address', models.CharField(blank=True, max_length=255, null=True)),
                ('kra_pin', models.CharField(blank=True, max_length=255, null=True)),
                ('store_number', models.CharField(blank=True, max_length=255, null=True)),
                ('store_name', models.CharField(blank=True, max_length=255, null=True)),
                ('national_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_staff', models.IntegerField()),
                ('is_superuser', models.IntegerField()),
                ('is_vendor', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('vendor_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_email_varified', models.CharField(max_length=255)),
                ('varification_key', models.CharField(blank=True, max_length=255, null=True)),
                ('user_image', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('date_registered', models.DateTimeField()),
                ('date_updated', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ptz_account_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PtzCustomers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('county', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_fee', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('profile_image', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.CharField(max_length=255)),
                ('is_verified', models.CharField(max_length=30)),
                ('verification_key', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ptz_customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PtzProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255)),
                ('vendor_id', models.CharField(blank=True, max_length=255, null=True)),
                ('product_title', models.CharField(max_length=255)),
                ('shop_name', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('brand_id', models.IntegerField()),
                ('category_id', models.IntegerField()),
                ('subcategory_id', models.IntegerField()),
                ('sub_subcategory_id', models.IntegerField(blank=True, null=True)),
                ('product_tags', models.CharField(max_length=255)),
                ('product_sku', models.CharField(max_length=255)),
                ('product_qty', models.CharField(max_length=255)),
                ('selling_price', models.CharField(max_length=255)),
                ('discount_price', models.CharField(blank=True, max_length=255, null=True)),
                ('product_size', models.CharField(max_length=255)),
                ('product_color', models.CharField(blank=True, max_length=255, null=True)),
                ('product_material', models.CharField(blank=True, max_length=255, null=True)),
                ('end_date', models.CharField(blank=True, max_length=255, null=True)),
                ('product_thumbnail', models.CharField(max_length=255)),
                ('hot_deals', models.CharField(blank=True, max_length=255, null=True)),
                ('featured', models.CharField(blank=True, max_length=255, null=True)),
                ('is_recomended', models.IntegerField(blank=True, null=True)),
                ('special_offer', models.CharField(blank=True, max_length=255, null=True)),
                ('special_deals', models.CharField(blank=True, max_length=255, null=True)),
                ('value_of_the_day', models.IntegerField(blank=True, null=True)),
                ('weekly_offers', models.IntegerField(blank=True, null=True)),
                ('new_arrivals', models.IntegerField(blank=True, null=True)),
                ('short_description', models.TextField()),
                ('product_specification', models.TextField(blank=True, null=True)),
                ('long_description', models.TextField()),
                ('is_varified', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ptz_products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
