# Generated by Django 3.2.3 on 2022-09-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PtzAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('county', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_default', models.IntegerField(db_column='is-default')),
                ('address_type', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ptz_address',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PtzCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
                ('category_image', models.CharField(max_length=100)),
                ('category_thumbnail', models.CharField(max_length=100)),
                ('is_topcategory', models.IntegerField()),
                ('date_created', models.DateTimeField()),
                ('soft_delete', models.IntegerField()),
            ],
            options={
                'db_table': 'ptz_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PtzCustomers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('county', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_fee', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('profile_image', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.CharField(max_length=255)),
                ('is_verified', models.CharField(max_length=30)),
                ('verification_key', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ptz_customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PtzSubcategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('subcategory_name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField()),
                ('date_updated', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ptz_subcategories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PtzSubsubcategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('subcategory_id', models.IntegerField()),
                ('sub_subcategory_name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField()),
                ('date_updated', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ptz_subsubcategories',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
    ]
