# Generated by Django 4.0.4 on 2022-06-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiV1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PtzCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('category_icon', models.CharField(blank=True, max_length=255, null=True)),
                ('category_image', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField()),
            ],
            options={
                'db_table': 'ptz_categories',
                'managed': False,
            },
        ),
    ]
