# Generated by Django 3.2.3 on 2023-04-08 17:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apiV1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('f35435a7-9d73-47ec-9afc-5b1134eba1e3'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('category_name', models.CharField(max_length=30)),
                ('category_image', models.ImageField(blank=True, default='', null=True, upload_to='categories')),
                ('category_thumbnail', models.ImageField(blank=True, default='', null=True, upload_to='categories')),
                ('is_topcategory', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('soft_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategories',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('156889a1-4b92-4519-99a9-19339ae18fdc'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('subcategory_name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='apiV1.categories')),
            ],
        ),
        migrations.CreateModel(
            name='SubsubCategories',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('183a3c69-2c24-40d4-a726-244cde62d5e7'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='categories')),
                ('is_major', models.BooleanField(default=False)),
                ('ftype', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryID', to='apiV1.categories')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategoryID', to='apiV1.subcategories')),
            ],
        ),
    ]
