# Generated by Django 4.0.4 on 2022-06-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiV1', '0002_ptzcategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='PtzSubcategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField()),
                ('date_updated', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ptz_subcategories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PtzSubsubcategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('subcategory_id', models.IntegerField()),
                ('sub_subcategory_name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField()),
                ('date_updated', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ptz_subsubcategories',
                'managed': False,
            },
        ),
    ]
