# Generated by Django 3.2.3 on 2023-04-09 09:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apiV1', '0002_categories_subcategories_subsubcategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fcb8efbb-ed60-49fa-9745-8348c5a28480'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c969604e-6010-4538-98dd-7c8e8c9e0822'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subsubcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f825565e-266b-4b3b-b9ce-b02fc4d2e42a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
