# Generated by Django 3.2.3 on 2023-04-11 10:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apiV1', '0004_auto_20230409_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1ce06bb3-6d2c-47e8-9030-a907388c4e63'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1dbc1296-7a5f-4019-9402-5b6e37bb70a0'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subsubcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ce7779a6-5879-46c3-9c42-0cb1a4862953'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
