# Generated by Django 4.0.4 on 2022-06-09 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiV1', '0005_ptzmultipleimgs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ptzproducts',
            options={'ordering': ['-id']},
        ),
    ]
