# Generated by Django 3.2.3 on 2023-04-14 13:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apiV1', '0006_auto_20230414_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8f5175e8-00bd-416e-aa22-daa795a1ed94'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b6ef25bd-e861-4386-bf3a-5e3d53a4d076'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subsubcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4700ebd2-48b1-403c-9045-76c75839527b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
