# Generated by Django 3.2.3 on 2022-07-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiV1', '0006_alter_ptzproducts_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PtzBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('brand_title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('brand_image', models.CharField(max_length=255)),
                ('is_major', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField()),
                ('soft_delete', models.IntegerField()),
            ],
            options={
                'db_table': 'ptz_brands',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PtzMainslidersettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.CharField(max_length=255)),
                ('is_active', models.IntegerField()),
                ('main_slider', models.IntegerField(blank=True, null=True)),
                ('customer_slider', models.IntegerField(blank=True, null=True)),
                ('others', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField()),
                ('date_updated', models.IntegerField()),
                ('soft_delete', models.IntegerField()),
            ],
            options={
                'db_table': 'ptz_mainslidersettings',
                'managed': False,
            },
        ),
    ]
