# Generated by Django 3.2.3 on 2022-08-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiV1', '0007_ptzbrands_ptzmainslidersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='fistname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='lastname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
