# Generated by Django 3.2.3 on 2022-08-24 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiV1', '0008_auto_20220824_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='fistname',
            new_name='firstname',
        ),
    ]
