# Generated by Django 3.2.3 on 2023-04-16 19:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apiV1', '0009_auto_20230414_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('286fde96-ac97-4563-a8c6-cc96ad289455'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ca70ced8-6727-45d3-aca6-cbcbf1822d96'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subsubcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c3b1b170-3f86-4e74-93a1-bebfe4c51c39'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
