# Generated by Django 3.2.3 on 2022-08-24 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiV1', '0009_rename_fistname_account_firstname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
    ]
