# Generated by Django 3.2.3 on 2023-04-16 21:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apiV1', '0011_auto_20230416_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ebb1e61b-2e3e-4676-8151-73486311ebc4'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9fe1c682-0680-4322-969c-5eb38e3e91c7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subsubcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('77941db0-a40c-4fdc-9b1a-e08372b954fb'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
