# Generated by Django 3.2.3 on 2023-04-16 21:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apiV1', '0013_auto_20230416_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5c2e6a-d9cb-46a4-96d8-5c746685f335'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1157a0ea-6373-4b20-83fe-376e640f063f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subsubcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('95b7f241-159b-49f8-a93f-8bf6a8ec2cbb'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
