# Generated by Django 3.2.3 on 2023-04-18 08:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apiV1', '0019_auto_20230417_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9fecc5ac-698b-400b-ba1f-267da531640e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5eeca305-dc49-48a7-ac5d-7e816e1eff02'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subsubcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('932b43e3-093c-4508-9200-87bd7b4276ac'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
