# Generated by Django 3.2.3 on 2023-04-23 17:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apiV1', '0020_auto_20230418_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8b3a3384-7776-42f3-87d3-adc6acc31976'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a8973d90-2202-4126-87ac-36a87f42e6c0'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subsubcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ae867d61-9969-4cc4-97c1-752bfc971e0c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
