version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-prod
    command: gunicorn api.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/api/static
      - media_volume:/home/app/api/mediafiles
    expose:
      - "8000"
    env_file:
      - ./.env
    depends_on:
      - db
    links:
      - db:db
    networks:
      - freecodecamp
  db:
    image: postgres:13
    container_name: ecommerce_db
    restart: always
    volumes:
      - database-data:/var/lib/mysql/data/
    env_file:
      - ./.env.prod.db
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - freecodecamp

  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    volumes:
      - static_volume:/home/app/api/static
      - media_volume:/home/app/api/mediafiles
    depends_on:
      - web
    networks:
      - freecodecamp

volumes:
  database-data:
  static_volume:
  media_volume:
networks:
  freecodecamp: