version:  '3.8'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: patazone123
      MYSQL_DATABASE: admin_patazone
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - database-data:/var/lib/mysql/data/

volumes:
  database-data:


