version:  '3.8'
services:
  web:
    container_name: ecommerce-backend
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
    links:
      - db:db
    networks:
      - freecodecamp

  db:
    image: postgres:13
    container_name: ecommerce_db
    restart: always
    volumes:
      - database-data:/var/lib/mysql/data/
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - freecodecamp

  prometheus:
    image: prom/prometheus
    container_name: ecommerce_prometheus
    restart: no
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - web
    links:
      - web:web
    networks:
      - freecodecamp

  grafana:
    image: grafana/grafana
    container_name: ecommerce_grafana
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"
    restart: no
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - freecodecamp

volumes:
  database-data:
  prometheus_data:
  grafana_data:
networks:
  freecodecamp:


