global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    metrics_path: prometheus/metrics
    static_configs:
      - targets: ['ecommerce-backend:8000']