# Generated by Django 3.2.3 on 2022-12-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='auth_provider',
            field=models.CharField(default='email', max_length=255),
        ),
    ]
