# Generated by Django 3.2.3 on 2023-01-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_apps', '0002_account_auth_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
