# Generated by Django 3.2.3 on 2023-05-03 11:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('0e672a77-75c8-4704-ac3e-1b6c8c161524'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('category_name', models.CharField(max_length=30)),
                ('category_image', models.ImageField(blank=True, default='', null=True, upload_to='categories')),
                ('category_thumbnail', models.ImageField(blank=True, default='', null=True, upload_to='categories')),
                ('is_topcategory', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('soft_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategories',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('349d6406-602d-454f-a62f-c7eb46d17896'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('subcategory_name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='categories.categories')),
            ],
        ),
        migrations.CreateModel(
            name='SubsubCategories',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('74542e09-36cb-4160-aec6-69e292360934'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='categories')),
                ('is_major', models.BooleanField(default=False)),
                ('ftype', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryID', to='categories.categories')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategoryID', to='categories.subcategories')),
            ],
        ),
    ]
