# Generated by Django 3.2.3 on 2023-05-03 11:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20230503_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2e3d6b07-62ee-4953-9e91-aeb2c8d6809a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fdf36e51-eafe-4238-b44a-57c2c5b0b837'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subsubcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('15ec2d33-fcbb-4c62-9662-c59ac6371ed5'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
