# Generated by Django 3.2.3 on 2023-05-03 11:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20230503_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1c53e832-e8a5-46f1-8010-afb37d3507d5'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4624aab0-7ad5-4ae8-8e70-e68cd1b51440'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subsubcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('28c203f0-d594-48bb-a07c-99a14f942e2a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
