# Generated by Django 3.2.3 on 2023-05-03 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20230503_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3f56b02d-2474-4cc2-87cf-ae59d996fe03'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('11b79948-2450-4569-a406-fc1b56eb2b0b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subsubcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ae62d926-40de-49c3-b51c-4c861ccefee2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
