# Generated by Django 4.2.1 on 2023-05-30 13:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_auto_20230503_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8c124646-e117-42e4-80d0-7bd698019803'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('252ac71d-2529-4679-9bf8-dbb63b071e27'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subsubcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e2ebcaa1-f659-4299-b7ac-0a6d0cc0149e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
