# Generated by Django 4.2.1 on 2023-05-30 13:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_alter_categories_id_alter_subcategories_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e5c86422-3fdc-425e-a446-19f1380062c1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7675db7b-4a26-4691-9879-023d935058cd'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subsubcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('313bbff4-bf17-41c9-86a7-4de7903e1e66'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
