# Generated by Django 4.2.1 on 2023-06-01 17:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_alter_categories_id_alter_subcategories_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('08f19bd3-72fc-41c8-ac31-b3856d50a666'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5f3ae214-c892-4866-866e-00eae0bcf154'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subsubcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e96d1156-d535-4b31-8398-10e1f57c4441'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
