# Generated by Django 3.2.3 on 2023-04-16 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('9cb07dd6-3c00-4859-967a-0f28fd286bdc'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('county', models.CharField(blank=True, max_length=120, null=True)),
                ('region', models.CharField(blank=True, max_length=120, null=True)),
                ('street', models.CharField(blank=True, max_length=120, null=True)),
                ('address', models.CharField(blank=True, max_length=120, null=True)),
                ('latitude', models.CharField(blank=True, max_length=120, null=True)),
                ('longitude', models.CharField(blank=True, max_length=120, null=True)),
                ('address_type', models.CharField(blank=True, default='shipping', max_length=120, null=True)),
                ('is_default', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
