# Generated by Django 3.2.3 on 2023-04-16 19:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e822ec6a-3089-401d-8a49-5499572e9c9f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
