# Generated by Django 3.2.3 on 2023-04-16 21:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_alter_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6eabb860-6745-4a2e-8df8-1dd5be5d4862'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
