# Generated by Django 3.2.3 on 2023-04-16 21:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_alter_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9207a835-e227-4633-bb7e-de4cff65a6d6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
