# Generated by Django 3.2.3 on 2023-04-16 21:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_alter_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9fbaeeb2-46a2-45b0-860b-ada451902ade'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
