# Generated by Django 3.2.3 on 2023-04-16 21:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_alter_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.UUIDField(default=uuid.UUID('197f9430-8b2d-48e2-8ee6-1b18886768e6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
