# Generated by Django 3.2.3 on 2023-04-16 21:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_alter_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.UUIDField(default=uuid.UUID('93aacf12-b76a-4460-abe5-8f9ffae89cfd'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
