# Generated by Django 3.2.3 on 2023-04-17 06:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0008_alter_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1ffccda0-91e2-43aa-ae0e-fb8758620566'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
