# Generated by Django 3.2.3 on 2023-04-17 07:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0009_alter_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.UUIDField(default=uuid.UUID('73edb5d7-18bc-40c0-bec7-e2195b188b90'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
