# Generated by Django 3.2.3 on 2023-04-18 08:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0010_alter_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5e0c6ca0-5edf-48b6-8c90-377c33d4fc48'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
