# Generated by Django 3.2.3 on 2023-05-02 09:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0012_alter_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.UUIDField(default=uuid.UUID('010cef4c-5971-4652-ab59-a66c8f06d23b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
