# Generated by Django 3.2.3 on 2023-05-02 09:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0013_alter_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b1869969-af16-4337-8f49-9ae412bd4c00'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
