# Generated by Django 3.2.3 on 2023-05-03 11:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0015_alter_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c82687e5-1ba8-494c-ae01-eb8b1b8b6358'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
