# Generated by Django 3.2.3 on 2023-05-03 11:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0016_alter_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.UUIDField(default=uuid.UUID('36eb86b6-ee54-441f-9e4f-9b15ad540123'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
