# Generated by Django 3.2.3 on 2023-05-03 11:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0017_alter_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0d129901-7b38-439f-8a47-e0b5eea486ba'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
