# Generated by Django 3.2.3 on 2023-05-03 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0018_alter_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e6c4e6b0-b300-4a8c-865f-9b3f0a76ab9f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
