# Generated by Django 4.2.1 on 2023-05-30 13:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0019_alter_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1f1a192c-3359-48c7-a929-fd31a52c7dfb'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
