# Generated by Django 4.2.1 on 2023-05-30 13:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0020_alter_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.UUIDField(default=uuid.UUID('956c9726-288c-4932-b236-3dddc07eac23'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
