# Generated by Django 4.2.1 on 2023-06-01 17:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0021_alter_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.UUIDField(default=uuid.UUID('824405b2-1ad1-45b7-86a3-de6f6dd9f62e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
