# Generated by Django 4.2.1 on 2023-06-05 13:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0022_alter_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9797cc3b-0257-45b2-a0e7-cec021c4d62e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
