# Generated by Django 4.2.1 on 2023-06-08 21:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0023_alter_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b2a410cc-ed0e-4a2a-ad0b-bd5336a768fd'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
