# Generated by Django 4.2.1 on 2023-06-08 21:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0024_alter_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5c770e46-6e34-437a-b607-4f1bfd69225f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
