# Generated by Django 4.2.1 on 2023-06-08 21:49

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('address', models.TextField(max_length=500, null=True)),
                ('logo', models.ImageField(null=True, upload_to=products.models.imagePath)),
                ('copyrightTxt', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
