# Generated by Django 3.2.3 on 2023-04-09 11:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20230409_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('10bd74ba-8367-4a8f-8133-84a89b03a81a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('af419d40-6692-4f06-a7f4-277049321ebb'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subsubcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b8cc5f2a-d1ae-40eb-bcae-855093879718'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
