# Generated by Django 3.2.3 on 2023-04-14 09:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20230411_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('132784b3-641f-420f-9fdc-e6bc2277496d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2949299e-b1f2-4bbe-93ca-fabb1ac71fbd'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subsubcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b4cb46a3-1984-4a2e-a173-9acd0df7ffe2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
