# Generated by Django 3.2.3 on 2023-04-14 13:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20230414_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f6611b2a-a18a-43fa-a29c-e233ba2d1195'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c8ea808e-e440-4744-a2c0-e141a8b6cc6a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subsubcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d3a483a5-d82d-42a2-93ff-097889f1904f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
