# Generated by Django 3.2.3 on 2023-04-16 21:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20230416_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ce371342-a975-49ef-9893-2d6e204f6a10'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fb59832f-f4a6-47ac-b6e6-1fbc6f5b961c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subsubcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c607ff19-568c-4b91-9f54-9b4760aa5ce7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
