# Generated by Django 3.2.3 on 2023-04-16 21:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20230416_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a9885162-291c-483f-9285-eb1195d87889'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fa919515-ccb4-40d4-bd05-7ebd6c25d0aa'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subsubcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6d076af8-1054-404b-93fb-c06447be3852'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
