# Generated by Django 3.2.3 on 2023-04-17 06:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20230416_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('78dfdcff-3063-4c4b-9aeb-0e343c7c71cc'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dc31a24a-62ee-4177-bb5c-3e94f5d838a1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subsubcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6fbd12fe-f312-43fa-a526-8395b6937c56'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
