# Generated by Django 3.2.3 on 2023-04-17 07:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20230417_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3cc6bed7-af9b-4727-bba2-50cde90bf676'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c8e1e6e8-622a-4a27-868d-dd7b147baf71'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subsubcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0363b632-b1ab-46c4-9c08-f70da081d0f0'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
