# Generated by Django 3.2.3 on 2023-05-02 09:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20230423_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('30d97316-d653-4ea9-b436-c2c135ae3397'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2356e00b-b5e2-4408-aa2a-20576f42b36e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subsubcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('229ba25f-5e9d-42a4-a520-b9c384853807'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
