# Generated by Django 3.2.3 on 2023-05-02 09:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20230502_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b4f1cf83-cdbe-4f03-bd9d-d96ac4bc3279'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4e2f9964-428f-4371-a95c-75d0897cdc70'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subsubcategories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3c86ee63-297e-4009-86f9-cf9ee6e15667'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
