# Generated by Django 3.2.3 on 2023-05-03 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20230503_1120'),
        ('base', '0023_auto_20230502_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategories',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subsubcategories',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subsubcategories',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Subcategories',
        ),
        migrations.DeleteModel(
            name='SubsubCategories',
        ),
    ]
