# Generated by Django 4.2.1 on 2023-05-30 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20230503_1120'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PtzAddress',
        ),
        migrations.DeleteModel(
            name='PtzCategories',
        ),
        migrations.DeleteModel(
            name='PtzCustomers',
        ),
        migrations.DeleteModel(
            name='PtzSubcategories',
        ),
        migrations.DeleteModel(
            name='PtzSubsubcategories',
        ),
    ]
