# Generated by Django 3.2.3 on 2022-09-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PtzCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True)),
                ('user_id', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('product_qty', models.IntegerField()),
                ('product_price', models.CharField(max_length=255)),
                ('product_size', models.CharField(blank=True, max_length=255, null=True)),
                ('product_color', models.CharField(blank=True, max_length=255, null=True)),
                ('ordered', models.IntegerField()),
                ('discounted_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('discount_price', models.CharField(blank=True, max_length=255, null=True)),
                ('shop_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_image', models.CharField(max_length=255)),
                ('product_material', models.CharField(blank=True, max_length=255, null=True)),
                ('product_number', models.CharField(max_length=255)),
                ('product_sku', models.CharField(max_length=255)),
                ('product_slug', models.CharField(max_length=255)),
                ('soft_delete', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ptz_cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PtzOrders',
            fields=[
                ('order_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_id', models.CharField(max_length=255)),
                ('coupon_id', models.IntegerField(blank=True, null=True)),
                ('amount_paid', models.CharField(blank=True, max_length=255, null=True)),
                ('county', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_fee', models.CharField(blank=True, max_length=255, null=True)),
                ('discount', models.CharField(blank=True, max_length=255, null=True)),
                ('is_paid', models.IntegerField()),
                ('order_notes', models.TextField(blank=True, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=255, null=True)),
                ('order_status', models.CharField(max_length=255)),
                ('user_type', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField()),
                ('soft_delete', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ptz_orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='tbl_orders',
            fields=[
                ('date_created', models.DateTimeField(auto_created=True)),
                ('order_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_id', models.CharField(max_length=255)),
                ('coupon_id', models.IntegerField(blank=True, null=True)),
                ('amount_paid', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_fee', models.CharField(blank=True, max_length=255, null=True)),
                ('discount', models.CharField(blank=True, max_length=255, null=True)),
                ('is_paid', models.IntegerField(default=0, max_length=10)),
                ('order_notes', models.TextField(blank=True, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=255, null=True)),
                ('order_status', models.CharField(max_length=255)),
                ('user_type', models.CharField(max_length=255)),
                ('soft_delete', models.CharField(max_length=50)),
            ],
        ),
    ]
