# Generated by Django 3.2.3 on 2023-04-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_orders',
            name='is_paid',
            field=models.IntegerField(default=0),
        ),
    ]
