# Generated by Django 3.2.3 on 2023-04-16 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0005_auto_20230416_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.UUIDField(default=uuid.UUID('09ee006a-318f-419d-84ac-2da55cb0bb75'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
