# Generated by Django 3.2.3 on 2023-04-16 21:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_orders_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.orders'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fc8ead81-2b6b-484e-bbbc-97028628afb9'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
