# Generated by Django 3.2.3 on 2023-04-17 07:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20230417_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.orders'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.UUIDField(default=uuid.UUID('18dc4986-1471-48d8-91b2-53e1e190d9f7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
