# Generated by Django 3.2.3 on 2023-04-18 08:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20230417_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='amount_paid',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1e66a1c1-965d-4610-9ab1-d3e781a494d9'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
