# Generated by Django 3.2.3 on 2023-04-23 17:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20230418_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.UUIDField(default=uuid.UUID('71340d02-3720-4ac6-ad92-e08f51ba55e8'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
