# Generated by Django 3.2.3 on 2023-05-02 09:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_orders_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6c55367d-fb5c-43a9-a4de-99d23f4a1b5f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
