# Generated by Django 3.2.3 on 2023-05-02 09:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_orders_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f39c8f79-0515-47e2-bffb-30b7b2b3aa94'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
