# Generated by Django 3.2.3 on 2023-05-03 11:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_orders_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dbee89b0-9e98-403e-b2f9-22ccbf8bdfd9'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
