# Generated by Django 3.2.3 on 2023-05-03 11:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_orders_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5b77f73c-03c7-4495-b823-ce951acf7ffc'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
