# Generated by Django 4.2.1 on 2023-05-30 13:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_orders_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PtzCart',
        ),
        migrations.DeleteModel(
            name='PtzOrders',
        ),
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ea610436-b9db-409d-9940-2f1aeb77b2b6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
