# Generated by Django 4.2.1 on 2023-05-30 13:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_delete_ptzcart_delete_ptzorders_alter_orders_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9b36b9d1-5d7e-4e29-ac23-7a1f7dbac2ed'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
