# Generated by Django 3.2.3 on 2023-04-14 13:42

from django.db import migrations, models
import django.db.models.deletion
import products.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0009_auto_20230414_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='PtzBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('brand_title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('brand_image', models.CharField(max_length=255)),
                ('is_major', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField()),
                ('soft_delete', models.IntegerField()),
            ],
            options={
                'db_table': 'ptz_brands',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PtzMainslidersettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.CharField(max_length=255)),
                ('is_active', models.IntegerField()),
                ('main_slider', models.IntegerField(blank=True, null=True)),
                ('customer_slider', models.IntegerField(blank=True, null=True)),
                ('others', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField()),
                ('date_updated', models.IntegerField()),
                ('soft_delete', models.IntegerField()),
            ],
            options={
                'db_table': 'ptz_mainslidersettings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PtzMultipleimgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('img_url', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField()),
            ],
            options={
                'db_table': 'ptz_multipleimgs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('brand_id', models.UUIDField(default=uuid.UUID('8b7a0c8e-a0ea-465a-a6f3-61fdfecba226'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('brand_title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('brand_image', models.ImageField(upload_to='brands')),
                ('is_major', models.BooleanField(blank=True, default=False, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.UUID('e3a317f1-106e-4bef-b2e8-5f3446d13067'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_title', models.CharField(max_length=255)),
                ('shop_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('product_tags', models.CharField(max_length=255)),
                ('product_sku', models.CharField(blank=True, max_length=255)),
                ('product_qty', models.IntegerField(default=0)),
                ('selling_price', models.FloatField(max_length=255)),
                ('discount_price', models.FloatField(blank=True, default=0.0, max_length=255, null=True)),
                ('variation', models.JSONField(blank=True, null=True)),
                ('barcode', models.CharField(blank=True, max_length=255, null=True)),
                ('product_thumbnail', models.ImageField(upload_to=products.models.imagePath)),
                ('hot_deals', models.BooleanField(blank=True, default=False, null=True)),
                ('featured', models.BooleanField(blank=True, default=False, null=True)),
                ('recommended', models.BooleanField(blank=True, default=False, null=True)),
                ('short_description', models.TextField()),
                ('product_specification', models.TextField(blank=True, null=True)),
                ('long_description', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brands')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='base.categories')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='base.subcategories')),
                ('subsubcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsubcategory', to='base.subsubcategories')),
            ],
        ),
        migrations.CreateModel(
            name='PtzProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255)),
                ('vendor_id', models.CharField(blank=True, max_length=255, null=True)),
                ('product_title', models.CharField(max_length=255)),
                ('shop_name', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('brand_id', models.IntegerField()),
                ('category_id', models.IntegerField()),
                ('subcategory_id', models.IntegerField()),
                ('sub_subcategory_id', models.IntegerField(blank=True, null=True)),
                ('product_tags', models.CharField(max_length=255)),
                ('product_sku', models.CharField(blank=True, max_length=255)),
                ('product_qty', models.CharField(max_length=255)),
                ('selling_price', models.CharField(max_length=255)),
                ('discount_price', models.CharField(blank=True, max_length=255, null=True)),
                ('product_size', models.CharField(max_length=255)),
                ('product_color', models.CharField(blank=True, max_length=255, null=True)),
                ('product_material', models.CharField(blank=True, max_length=255, null=True)),
                ('end_date', models.CharField(blank=True, max_length=255, null=True)),
                ('product_thumbnail', models.CharField(max_length=255)),
                ('hot_deals', models.CharField(blank=True, max_length=255, null=True)),
                ('featured', models.CharField(blank=True, max_length=255, null=True)),
                ('is_recomended', models.IntegerField(blank=True, null=True)),
                ('special_offer', models.CharField(blank=True, max_length=255, null=True)),
                ('special_deals', models.CharField(blank=True, max_length=255, null=True)),
                ('value_of_the_day', models.IntegerField(blank=True, null=True)),
                ('weekly_offers', models.IntegerField(blank=True, null=True)),
                ('new_arrivals', models.IntegerField(blank=True, null=True)),
                ('short_description', models.TextField()),
                ('product_specification', models.TextField(blank=True, null=True)),
                ('long_description', models.TextField()),
                ('is_varified', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ptz_products',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default='', null=True, upload_to=products.models.imagePath)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
    ]
