# Generated by Django 3.2.3 on 2023-04-16 19:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230416_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='brand_id',
            field=models.UUIDField(default=uuid.UUID('c3a7ddf1-08df-4412-8e61-ce1decf618b5'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('64c3097d-84ab-4edf-9fa1-e8002da50486'), primary_key=True, serialize=False, unique=True),
        ),
    ]
