# Generated by Django 3.2.3 on 2023-04-16 21:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230416_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='brand_id',
            field=models.UUIDField(default=uuid.UUID('9570ee25-e167-471d-bd17-30f9fc3c0a7c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('d9721376-6c1e-4b00-89ae-18cd9ef4f8f4'), primary_key=True, serialize=False, unique=True),
        ),
    ]
