# Generated by Django 3.2.3 on 2023-04-08 17:46

from django.db import migrations, models
import django.db.models.deletion
import products.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apiV1', '0002_categories_subcategories_subsubcategories'),
        ('products', '0004_alter_ptzproducts_product_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('brand_id', models.UUIDField(default=uuid.UUID('2c1969c2-d1b5-4691-a8dc-d15821cc5a89'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('brand_title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('brand_image', models.ImageField(upload_to='brands')),
                ('is_major', models.BooleanField(blank=True, default=False, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiV1.categories')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('product_id', models.UUIDField(default=uuid.UUID('050390eb-72b2-4ec1-834e-3414be7a9752'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_title', models.CharField(max_length=255)),
                ('shop_name', models.CharField(max_length=255)),
                ('c', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('product_tags', models.CharField(max_length=255)),
                ('product_sku', models.CharField(blank=True, max_length=255)),
                ('product_qty', models.IntegerField(default=0)),
                ('selling_price', models.FloatField(max_length=255)),
                ('discount_price', models.FloatField(blank=True, max_length=255, null=True)),
                ('variation', models.JSONField(blank=True, null=True)),
                ('barcode', models.CharField(blank=True, max_length=255, null=True)),
                ('product_thumbnail', models.ImageField(upload_to=products.models.imagePath)),
                ('hot_deals', models.BooleanField(blank=True, default=False, null=True)),
                ('featured', models.BooleanField(blank=True, default=False, null=True)),
                ('recommended', models.BooleanField(blank=True, default=False, null=True)),
                ('short_description', models.TextField()),
                ('product_specification', models.TextField(blank=True, null=True)),
                ('long_description', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brands')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='apiV1.categories')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='apiV1.subcategories')),
                ('subsubcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsubcategory', to='apiV1.subsubcategories')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default='', null=True, upload_to=products.models.imagePath)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productmodel')),
            ],
        ),
    ]
