# Generated by Django 3.2.3 on 2023-04-16 21:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20230416_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='brand_id',
            field=models.UUIDField(default=uuid.UUID('6c56b3cf-40f0-4972-808d-b3c206e57f85'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('f99a31bf-b8ca-4ff2-b989-764b4165475d'), primary_key=True, serialize=False, unique=True),
        ),
    ]
