# Generated by Django 3.2.3 on 2023-04-09 09:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_brands_productimages_productmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='c',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='brands',
            name='brand_id',
            field=models.UUIDField(default=uuid.UUID('d544ec6a-a52c-423f-9078-9a80388f3eea'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('451cb2d3-79cd-4ab5-9c91-682a8c883512'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
