# Generated by Django 3.2.3 on 2023-04-16 21:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20230416_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='brand_id',
            field=models.UUIDField(default=uuid.UUID('948da3d0-7a5c-488c-9871-82cb663f1389'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('b829287a-4965-4c57-a655-6d25624f438d'), primary_key=True, serialize=False, unique=True),
        ),
    ]
