# Generated by Django 3.2.3 on 2023-04-16 21:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20230416_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='brand_id',
            field=models.UUIDField(default=uuid.UUID('83da327b-682f-4586-9f49-0ab4f64bad0e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('23c7acd9-6399-4003-80d7-be424ce72c32'), primary_key=True, serialize=False, unique=True),
        ),
    ]
