# Generated by Django 3.2.3 on 2023-04-09 11:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20230409_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='brand_id',
            field=models.UUIDField(default=uuid.UUID('7ad233db-88b5-4b09-b4ca-d535aa2a1d84'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('c3fc9995-7b07-4df6-8b30-b1a0ef8362a5'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
