# Generated by Django 3.2.3 on 2023-04-11 10:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20230409_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='brand_id',
            field=models.UUIDField(default=uuid.UUID('d3744f43-1e44-4c70-99ff-0765728262bd'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='discount_price',
            field=models.FloatField(blank=True, default=0.0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('196ed4e7-5db2-4c1c-af82-082269da76e1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
