# Generated by Django 3.2.3 on 2023-04-14 09:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20230411_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='brand_id',
            field=models.UUIDField(default=uuid.UUID('69cfbe6b-58c4-484d-bba8-3e3aff53404e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('2a8a2f5b-a03c-45e3-87fa-0963c7b10bd2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
