# Generated by Django 3.2.3 on 2023-04-16 21:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20230416_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='brand_id',
            field=models.UUIDField(default=uuid.UUID('ccc38b44-7551-4954-b68a-a06f50f443ed'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('e4a0035e-34fa-49b6-a879-34ca0865731e'), primary_key=True, serialize=False, unique=True),
        ),
    ]
