# Generated by Django 3.2.3 on 2023-04-17 06:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20230416_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='brand_id',
            field=models.UUIDField(default=uuid.UUID('1d8f66df-daa8-414a-84a6-2b1efa3270c1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('088836c1-1bf6-40a6-8fe5-a6c45ec70c27'), primary_key=True, serialize=False, unique=True),
        ),
    ]
