# Generated by Django 3.2.3 on 2023-04-18 08:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20230417_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='brand_id',
            field=models.UUIDField(default=uuid.UUID('0fd9edac-d3be-4e72-868d-118e22c0a0b7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('114adbc9-57d5-448f-8474-0fa724aad281'), primary_key=True, serialize=False, unique=True),
        ),
    ]
