# Generated by Django 3.2.3 on 2023-04-23 17:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20230418_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='brand_id',
            field=models.UUIDField(default=uuid.UUID('9682467b-cb29-4fc4-947a-408e5143fb9b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('55345f74-2877-4eca-9597-2a71565d5f7d'), primary_key=True, serialize=False, unique=True),
        ),
    ]
