# Generated by Django 3.2.3 on 2023-05-02 09:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20230502_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='brand_id',
            field=models.UUIDField(default=uuid.UUID('33d90d59-217e-4a30-ad46-a90538fc3687'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('9e05a6ff-8dbd-444f-8549-4bf5aff7ade3'), primary_key=True, serialize=False, unique=True),
        ),
    ]
