# Generated by Django 3.2.3 on 2023-05-03 11:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20230503_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='brand_id',
            field=models.UUIDField(default=uuid.UUID('26a0c41f-a7bc-401f-a961-ea23f58e3dcd'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('85781daa-32ca-4b5d-95c6-ff4e6ab2ac18'), primary_key=True, serialize=False, unique=True),
        ),
    ]
