# Generated by Django 3.2.3 on 2023-05-03 11:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20230503_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='brand_id',
            field=models.UUIDField(default=uuid.UUID('1a12f6e9-6497-4cd4-8208-fbb32440e075'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('6c861be9-0275-4650-a4db-3556cbca0bf1'), primary_key=True, serialize=False, unique=True),
        ),
    ]
