# Generated by Django 3.2.3 on 2023-05-03 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20230503_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='brand_id',
            field=models.UUIDField(default=uuid.UUID('bf37e37d-43d9-499e-bf55-11f75b16098e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('3197e6cc-1459-4266-8be8-99f9ef70af3c'), primary_key=True, serialize=False, unique=True),
        ),
    ]
