# Generated by Django 4.2.1 on 2023-05-30 13:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20230503_1127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PtzProducts',
        ),
        migrations.DeleteModel(
            name='PtzBrands',
        ),
        migrations.DeleteModel(
            name='PtzMainslidersettings',
        ),
        migrations.DeleteModel(
            name='PtzMultipleimgs',
        ),
        migrations.AlterField(
            model_name='brands',
            name='brand_id',
            field=models.UUIDField(default=uuid.UUID('630f7bbd-7e5f-40ad-a7d8-a1a0f1d86a02'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('ee0a492c-4c9c-410f-9d27-f90a1823f7cf'), primary_key=True, serialize=False, unique=True),
        ),
    ]
