# Generated by Django 4.2.1 on 2023-05-30 13:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_delete_ptzproducts_delete_ptzbrands_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_tags',
            new_name='meta_title',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='shop_name',
            new_name='vendor',
        ),
        migrations.AddField(
            model_name='product',
            name='hyper_local_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='live',
            field=models.CharField(default='Draft', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='max_order_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='min_order_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='next_day_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='out_of_stock_sell',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='replaceable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='return_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='returnable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='same_day_deliver',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='brands',
            name='brand_id',
            field=models.UUIDField(default=uuid.UUID('6acd011a-2165-4095-b422-8268bb9b566c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.brands'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('7c20a393-ba5c-4420-a8e2-bee52fad4cb3'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_sku',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.FloatField(max_length=10),
        ),
    ]
